### ISSUE TITLE
Branding Issues

### ISSUE THREAD

**Issue by mattatobin** [rstefko/palemoon-expire-history-by-days#1]
So did you actually get permission from Marco Bonardo to create a fork of an extension using his extension name and icon? Because as a Firefox Team Engineering Consultant I seriously doubt he would allow that for a rival project especially seeing as the thing in its WebExtension form is still active.

For the record, the MPL does not extend to the use of any trademarks, servicemarks, or logos without express permission.

**Comment by rstefko** [comment]
I left the copyright as it was with Marco's name there. @mak77 are you OK with that?

**Comment by mak77** [comment]
Thank you for the notice. No concerns on my side, the icon was public domain anyway, and the name I picked is generic, on purpose!
I don't mind about "rival" projects, users should be free to choose their browser.

The only note I could make, is that I'm not really co-author of this specific add-on, so I'd prefer to not be in the creator field. Maybe the description could have "Based on Expire History By Days add-on by Marco Bonardo" at the end. But I'd be fine even with just the readme.md back link.

**Comment by mattatobin** [comment]
I believe properly you'd be in an `em:contributor` field in the `RDF Install Manifest`. But thank you very much @mak77 for being one of the few people left in the Mozillasphere that are still awesome! It personally really made my day.
